site_name: mkdocs-test
repo_url: https://github.com/ae9is/mkdocs-test
repo_name: ae9is/mkdocs-test
edit_uri: edit/main/packages/docs/docs/
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.action.view
  icon:
    edit: material/pencil 
    view: material/eye
